image: gcc:9.3.0-buster

stages:
  - deps
  - build

deps:libear:
  stage: deps

  before_script:
    - apt update && apt install -y cmake libboost-dev
  script:
    - git clone --recursive https://github.com/ebu/libear.git && cd libear/
    - mkdir build && cd build
    - cmake .. -DCMAKE_INSTALL_PREFIX=../install
    - make install

  artifacts:
    paths:
      - ./install/libear.a
      - ./install/include

deps:libadm:
  stage: deps

  before_script:
    - apt update && apt install -y cmake libboost-dev
  script:
    - git clone --branch 0.11.0 https://github.com/IRT-Open-Source/libadm.git && cd libadm/
    - mkdir build && cd build
    - cmake .. -DCMAKE_INSTALL_PREFIX=../install
    - make install

  artifacts:
    paths:
      - ./install/lib/libadm.a
      - ./install/include

deps:libbw64:
  stage: deps

  before_script:
    - apt update && apt install -y cmake libboost-dev
  script:
    - git clone --branch 0.10.0 https://github.com/IRT-Open-Source/libbw64.git && cd libbw64/
    - mkdir build && cd build
    - cmake .. -DCMAKE_INSTALL_PREFIX=../install
    - make install

  artifacts:
    paths:
      - ./install/include


build:
  stage: build

  before_script:
    - apt update && apt install -y cmake libboost-dev
  script:
    - mkdir build && cd build
    - cmake .. -DCMAKE_INSTALL_PREFIX=../install
    - make install
  needs: [
    "deps:libear",
    "deps:libadm",
    "deps:libbw64"
  ]
  artifacts:
    paths:
      - ./install/bin/adm-engine
      - ./install/lib/libadmengine.so
      - ./install/lib/libadmengine.a
      - ./install/include
